# Site settings
title: Paul D. Rowe
email: pauldavidrowe@gmail.com
description: >- 
  The personal webpage of Paul Rowe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: SidikiXavier
github_username:  pauldavidrowe
# Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
masthead: /images/pdr-logo.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

kramdown:
  math_engine: katex
  
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
